# Generated by Django 4.0.1 on 2022-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='end',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
