# Generated by Django 4.0.1 on 2022-03-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resume_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
