# Generated by Django 4.0.1 on 2022-03-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_resume_end'),
        ('main', '0004_delete_hello'),
    ]

    operations = [
    ]
