# Generated by Django 4.0.1 on 2022-03-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_0004_alter_resume_end_0004_delete_hello'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='email',
            new_name='gmail',
        ),
    ]
