# Generated by Django 4.0.1 on 2022-03-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_email_messages_gmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='gmail',
            new_name='email',
        ),
    ]
