# Generated by Django 4.0.1 on 2022-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='text3',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
