# Generated by Django 4.0.1 on 2022-03-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_commentofportfolio_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Port',
        ),
    ]
