# Generated by Django 4.0.1 on 2022-03-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_portfolio_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentofportfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='city',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='data',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='text',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='title',
        ),
        migrations.AddField(
            model_name='portfolios',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_cat', to='main.category'),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='client',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='domen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='photo1',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='photo2',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='photo3',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='photo4',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='tools',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commentofportfolio',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentofportfolio',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_port', to='main.portfolios'),
        ),
        migrations.AlterField(
            model_name='commentofportfolio',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='viewers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
