# Generated by Django 4.0.1 on 2022-03-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_commentofportfolio_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolios',
            old_name='client',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='portfolios',
            old_name='photo1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='portfolios',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='portfolios',
            old_name='domen',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='tools',
        ),
    ]
