# Generated by Django 4.0.1 on 2022-03-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_client_portfolios_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='image',
            field=models.ImageField(default='image', upload_to='media'),
            preserve_default=False,
        ),
    ]
