# Generated by Django 4.0.1 on 2022-03-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_portfolios_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_cat', to='main.category'),
        ),
    ]
