# Generated by Django 4.0.1 on 2022-03-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_commentofportfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
