# Generated by Django 4.0.1 on 2022-03-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_portfolios_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentofPortfolio',
        ),
        migrations.DeleteModel(
            name='Portfolios',
        ),
    ]
