# Generated by Django 4.0.1 on 2022-03-19 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_remove_commentofportfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentofportfolio',
            name='portfolios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_port', to='main.portfolios'),
        ),
        migrations.AlterField(
            model_name='commentofportfolio',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
