# Generated by Django 4.0.1 on 2022-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentofportfolio',
            name='reply',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
